---
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

name: Zgłoś błąd
description: Uzupełnij złoszenie błędu, żebyśmy lepiej zrozumieli, jak go naprawić.
title: "bug(<scope>): <title>"
labels: ["bug"]
# TODO: Add your team's assignees
# assignees:
body:
  - type: markdown
    attributes:
      value: |
        Dziękujemy za przesłanie zgłoszenia dotyczącego nowej funkcji!
        Prosimy o uzupełnienie poniższych informacji, aby dokładnie opisać swoją propozycję.
        Zwróć także uwagę, czy **scope** i **title** zgłoszenia są właściwie określone.

  # Why
  - type: textarea
    id: why-bug
    attributes:
      label: Dlaczego jest to błąd?
      description: Wyjaśnij, dlaczego to zachowanie jest błędne.
      placeholder: Np. potrzebuję być w stanie zrobić X, ponieważ Y.
    validations:
      required: true

  # What
  - type: textarea
    id: what-bug
    attributes:
      label: Na co wpływa ten błąd?
      description: Wyjasnij, które części systemu są nie działają przez to poprawnie.
      placeholder: Np. nadzorowanie, wysyłanie wiadomości, profile tekstu.
    validations:
      required: true

  # Who
  - type: textarea
    id: who-bug
    attributes:
      label: Na czyją pracę wpływa ten błąd?
      description: Wyjasnij, kto nie jest w stanie poprawnie pracować przez ten błąd.
      placeholder: Np. Wszyscy nadzorcy, Sally Supervisor, Poziom 1 CCs.
    validations:
      required: true

  # When
  - type: textarea
    id: when-bug
    attributes:
      label: Kiedy ten błąd występuje?
      description: Wyjasnij, kiedy i w jakich okolicznościach ten błąd występuje.
      placeholder: Np. Po zakończeniu konwersacji, co dzień o godzinie 3, kiedy zapiszę plik.
    validations:
      required: true

  # Where
  - type: textarea
    id: where-bug
    attributes:
      label: Gdzie na platformie występuje ten błąd?
      description: Wyjasnij, gdzie na platformie ten błąd występuje.
      placeholder: Np. W chatcie nadzorcy, na stronie profilu konwersacji, na ekranie uwierzytelniania dwuskładnikowego.
    validations:
      required: true

  # How
  - type: textarea
    id: how-bug
    attributes:
      label: Jak możemy to zreprodukować?
      description: Wyjasnij, jak możemy to zreprodukować.
      placeholder: Proszę o szczegółowość. Użyj myślników (-) lub liczb (1.) do tworzenia listy kroków.
    validations:
      required: true

  # Expected behavior (i.e. solution)
  - type: textarea
    id: expected-bug
    attributes:
      label: Oczekiwane zachowanie (np. rozwiązanie)
      description: Wyjasnij, co powinno się stać.
    validations:
      required: true

  # Other Comments
  - type: textarea
    id: other-comments
    attributes:
      label: Inne komentarze / logi
      description: Wyjaśnij dodatkowe rzeczy, które uważasz że są istotne.
